install.packages("qcc")
library(qcc)
data(pistonrings)
attach(pistonrings)
diameter <- qcc.groups(diameter, sample)
qcc(diameter[1:25,], type="xbar")
head(pistonrings)
head(pistonrings, n=3)
tail(pistonrings)
